### ISSUE TITLE
nevermind. 

### ISSUE THREAD

**Issue by thejford** [lonacluka/HP-EliteBook-840-G6-Hackintosh#4]
Had to use hardwired Ethernet connection to connect to the internet. No WiFi device could be found. Trackpad fixed, turned off Force Touch.

**Comment by thejford** [comment]
If I'd just read... intel cards aren't supported a lot of the time. The kext that might work is there, but it doesn't.

**Comment by lonacluka** [comment]
If you have this laptop your wifi should be intel ax200 and should work great with itlwm or airportitlwm. You can check for example with Hackintool under PCI devices what is your wifi chip. Try with itlwm and Heliport instead of airportitlwm, but both should work just fine.
https://openintelwireless.github.io/itlwm/FAQ.html#installation 

 If you want perfect wifi/bluetooth with all apple stuff working OOB consider replacing intel wifi with broadcom 94360ng (50$ on aliexpress), no extra kexts needed.

**Comment by lonacluka** [comment]
Do you dual boot with Windows? Maybe this is why your wifi is not working. https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi#about_dual-boot_with_windows_and_fast-boot_enabled

Try doing a cold start (dont restart from windows, but turn off pc by holding the power on button).

**Comment by thejford** [comment]
I don't dual boot. I have the card ordered. Machine runs like a champ, thanks for the work you did.

**Comment by lonacluka** [comment]
glad to hear!
